using System;
using System.Collections.Generic;

namespace PointOfSale.Core.Models.Inventory
{
    public class StockTransfer
    {
        public int BranchId { get; set; }
        public long TransferId { get; set; }
        public string TransferNumber { get; set; } // Generated by DB sequence
        public int FromLocationId { get; set; }
        public int ToLocationId { get; set; }
        public DateTime TransferDate { get; set; }
        public string Status { get; set; } = "Completed"; // Default status
        public string Note { get; set; }
        public int CreatedBy { get; set; }

        // Display properties (populated by history queries)
        public string FromLocationName { get; set; }
        public string ToLocationName { get; set; }
        public string Username { get; set; }

        // List of items to save
        public List<StockTransferLine> Lines { get; set; } = new List<StockTransferLine>();
    }
}
