using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Runtime.CompilerServices;

namespace PointOfSale.Core.Models.Inventory
{
    public class StockTransfer
    {
        public int BranchId { get; set; }
        public long TransferId { get; set; }
        public string TransferNumber { get; set; } // Generated by DB sequence
        public int FromLocationId { get; set; }
        public int ToLocationId { get; set; }
        public DateTime TransferDate { get; set; }
        public string Status { get; set; } = "Completed"; // Default status
        public string Note { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }

        // Display properties (populated by history queries)
        public string FromLocationName { get; set; }
        public string ToLocationName { get; set; }
        public string Username { get; set; }

        // List of items to save
        public List<StockTransferLine> Lines { get; set; } = new List<StockTransferLine>();


        private bool _isExpanded;
        public bool IsExpanded
        {
            get => _isExpanded;
            set => SetProperty(ref _isExpanded, value);
        }



        public event PropertyChangedEventHandler PropertyChanged;

        protected virtual void OnPropertyChanged([CallerMemberName] string propertyName = null)
        {
            PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));
        }

        protected bool SetProperty<T>(ref T storage, T value, [CallerMemberName] string propertyName = null)
        {
            if (EqualityComparer<T>.Default.Equals(storage, value)) return false;
            storage = value;
            OnPropertyChanged(propertyName);
            return true;
        }
    }
}
