using System;
using System.Collections.Generic;

namespace PointOfSale.Core.Models.Inventory
{
    public class Wastage
    {
        public long Id { get; set; }
        public int BranchId { get; set; }
        public int LocationId { get; set; }
        public string WastageNumber { get; set; } // Generated by SP
        public DateTime WastageDate { get; set; }
        public string Note { get; set; }
        public string Status { get; set; } // 'Posted'
        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; } = DateTime.Now;

        public List<WastageLine> Lines { get; set; } = new List<WastageLine>();
    }
}
